spring.application.name=smart-shop

#spring.datasource.url=jdbc:postgresql://localhost:5433/smart_link
#spring.datasource.username=postgres
#spring.datasource.password=Hour1819
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.main.allow-circular-references=true

#
## JPA (optional)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:postgresql://ep-polished-flower-a1hcns4i-pooler.ap-southeast-1.aws.neon.tech:5432/smart_link?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_xWZ4N8SnXHkl
spring.datasource.driver-class-name=org.postgresql.Driver

# (Optional) Connection pool settings for better performance
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000

server.port=8080

jwt.secret.key=da2bd42bef8f9f957d647ed13571d35b59c7055fb723eacdb05154878da17d77d3180385fc232cab38bded0fc7dbda0d439cc275e91164ade266d64d50633bc7
jwt.expiration-min=9999999999999